apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-16T06:14:57Z"
  name: "hyperschedule-dev"
spec:
  volumes:
    - name: "hyperschedule-dev-db"
      hostPath:
        path: "./.db/data"
        type: "DirectoryOrCreate"
  containers:
    - image: "docker.io/library/postgres:latest"
      args:
        - "postgres"
      command:
        - "docker-entrypoint.sh"
      env:
        - name: "POSTGRES_PASSWORD"
          value: "cool orange banana peels"
      name: "hyperschedule-dev-postgres"
      ports:
        - containerPort: 5432
          hostPort: 2345
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: "hyperschedule-dev-db"
      workingDir: "/"
    - image: "docker.io/library/redis:latest"
      args:
        - "redis"
      command:
        - "docker-entrypoint.sh"
      ports:
        - containerPort: 6379
          hostPort: 9736
